'use client';

import { useState } from 'react';
import { FolderOpen, X, Settings, CheckCircle, AlertTriangle, Clock, Activity, BarChart3, Filter, Zap, Calendar, Scan, Eye, Image as ImageIcon, Sparkles, Zap as ZapIcon, Layers, FolderPlus, Copy, ArrowRight, Calendar as CalendarIcon, MapPin, Tag, Users, RefreshCw, Trash2, Edit2 } from 'lucide-react';

interface OrganizationRule {
  id: string;
  name: string;
  type: 'date' | 'location' | 'category' | 'person' | 'event';
  enabled: boolean;
  autoApply: boolean;
  description: string;
}

interface SmartAlbum {
  id: string;
  name: string;
  type: 'date' | 'location' | 'person' | 'event' | 'custom';
  photoCount: number;
  lastUpdated: Date;
  autoGenerated: boolean;
}

interface DuplicateGroup {
  id: string;
  photos: Array<{
    id: string;
    name: string;
    similarity: number;
    size: number;
    date: Date;
  }>;
  action: 'keep_all' | 'keep_best' | 'keep_newest' | 'manual';
}

interface PhotoOrganizationProps {
  onCancel?: () => void;
  onRunOrganization?: () => Promise<void>;
  onCreateAlbum?: (name: string, type: string) => Promise<void>;
  onResolveDuplicates?: (groupId: string, action: string) => Promise<void>;
}

const DEFAULT_RULES: OrganizationRule[] = [
  {
    id: 'rule-1',
    name: 'Date-based',
    type: 'date',
    enabled: true,
    autoApply: true,
    description: 'Organize by date (YYYY/MM)',
  },
  {
    id: 'rule-2',
    name: 'Location-based',
    type: 'location',
    enabled: true,
    autoApply: true,
    description: 'Organize by GPS location',
  },
  {
    id: 'rule-3',
    name: 'Category-based',
    type: 'category',
    enabled: true,
    autoApply: false,
    description: 'Organize by scene category',
  },
  {
    id: 'rule-4',
    name: 'Person-based',
    type: 'person',
    enabled: true,
    autoApply: false,
    description: 'Organize by detected people',
  },
  {
    id: 'rule-5',
    name: 'Event-based',
    type: 'event',
    enabled: false,
    autoApply: false,
    description: 'Organize by events (birthday, vacation)',
  },
];

const DEFAULT_ALBUMS: SmartAlbum[] = [
  {
    id: 'album-1',
    name: '2024/01',
    type: 'date',
    photoCount: 45,
    lastUpdated: new Date('2024-01-12'),
    autoGenerated: true,
  },
  {
    id: 'album-2',
    name: 'Da Nang',
    type: 'location',
    photoCount: 32,
    lastUpdated: new Date('2024-01-10'),
    autoGenerated: true,
  },
  {
    id: 'album-3',
    name: 'Family',
    type: 'person',
    photoCount: 78,
    lastUpdated: new Date('2024-01-08'),
    autoGenerated: true,
  },
];

const DEFAULT_DUPLICATES: DuplicateGroup[] = [
  {
    id: 'dup-1',
    photos: [
      { id: 'p1', name: 'photo-1.jpg', similarity: 1.0, size: 2450, date: new Date('2024-01-12') },
      { id: 'p2', name: 'photo-1-copy.jpg', similarity: 0.98, size: 2400, date: new Date('2024-01-12') },
    ],
    action: 'keep_best',
  },
];

export default function PhotoOrganization({ onCancel, onRunOrganization, onCreateAlbum, onResolveDuplicates }: PhotoOrganizationProps) {
  const [rules, setRules] = useState<OrganizationRule[]>(DEFAULT_RULES);
  const [albums, setAlbums] = useState<SmartAlbum[]>(DEFAULT_ALBUMS);
  const [duplicates, setDuplicates] = useState<DuplicateGroup[]>(DEFAULT_DUPLICATES);
  const [showSettings, setShowSettings] = useState(false);
  const [isOrganizing, setIsOrganizing] = useState(false);
  const [selectedSort, setSelectedSort] = useState<'date' | 'location' | 'category'>('date');

  const totalAlbums = albums.length;
  const totalPhotos = albums.reduce((sum, a) => sum + a.photoCount, 0);
  const duplicateCount = duplicates.reduce((sum, d) => sum + d.photos.length, 0);
  const enabledRules = rules.filter(r => r.enabled).length;

  const getRuleIcon = (type: string) => {
    switch (type) {
      case 'date':
        return <CalendarIcon className="h-4 w-4" />;
      case 'location':
        return <MapPin className="h-4 w-4" />;
      case 'category':
        return <Tag className="h-4 w-4" />;
      case 'person':
        return <Users className="h-4 w-4" />;
      case 'event':
        return <Sparkles className="h-4 w-4" />;
      default:
        return <FolderOpen className="h-4 w-4" />;
    }
  };

  const getRuleColor = (type: string) => {
    switch (type) {
      case 'date':
        return 'text-blue-500';
      case 'location':
        return 'text-green-500';
      case 'category':
        return 'text-purple-500';
      case 'person':
        return 'text-pink-500';
      case 'event':
        return 'text-amber-500';
      default:
        return 'text-slate-500';
    }
  };

  const handleToggleRule = (ruleId: string) => {
    setRules(rules.map(r => 
      r.id === ruleId ? { ...r, enabled: !r.enabled } : r
    ));
  };

  const handleToggleAutoApply = (ruleId: string) => {
    setRules(rules.map(r => 
      r.id === ruleId ? { ...r, autoApply: !r.autoApply } : r
    ));
  };

  const handleRunOrganization = async () => {
    setIsOrganizing(true);
    await onRunOrganization?.();
    setIsOrganizing(false);
  };

  const handleResolveDuplicates = async (groupId: string, action: string) => {
    await onResolveDuplicates?.(groupId, action);
    setDuplicates(duplicates.map(d => 
      d.id === groupId ? { ...d, action: action as any } : d
    ));
  };

  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-lg border border-slate-200 dark:border-slate-700 p-6">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-gradient-to-br from-teal-400 to-cyan-500 rounded-xl">
            <FolderOpen className="h-5 w-5 text-white" />
          </div>
          <div>
            <h3 className="font-bold text-slate-900 dark:text-white text-lg">
              Tổ chức ảnh tự động
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              {totalAlbums} smart albums
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setShowSettings(!showSettings)}
            className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors"
            title="Cài đặt"
          >
            <Settings className="h-4 w-4 text-slate-500" />
          </button>
          <button
            type="button"
            onClick={onCancel}
            className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors"
            title="Đóng"
          >
            <X className="h-4 w-4 text-slate-500" />
          </button>
        </div>
      </div>

      {showSettings && (
        <div className="mb-4 p-4 bg-teal-50 dark:bg-teal-950/30 border border-teal-200 dark:border-teal-800 rounded-lg">
          <h4 className="font-semibold text-slate-900 dark:text-white text-sm mb-3">
            Cài đặt photo organization
          </h4>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs text-slate-600 dark:text-slate-400">
                Auto-organize on upload
              </span>
              <span className="text-xs text-green-600 dark:text-green-400 font-medium">Enabled</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-xs text-slate-600 dark:text-slate-400">
                Duplicate detection
              </span>
              <span className="text-xs text-green-600 dark:text-green-400 font-medium">Enabled</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-xs text-slate-600 dark:text-slate-400">
                Smart album creation
              </span>
              <span className="text-xs text-green-600 dark:text-green-400 font-medium">Enabled</span>
            </div>
          </div>
        </div>
      )}

      {/* Overall Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">
        <div className="p-3 rounded-xl border-2 bg-slate-50 dark:bg-slate-700/50 border-slate-200 dark:border-slate-600">
          <div className="flex items-center gap-2 mb-1">
            <Layers className="h-3 w-3 text-slate-500" />
            <span className="text-[10px] text-slate-600 dark:text-slate-400">Albums</span>
          </div>
          <div className="text-lg font-bold text-slate-900 dark:text-white">
            {totalAlbums}
          </div>
        </div>
        <div className="p-3 rounded-xl border-2 bg-slate-50 dark:bg-slate-700/50 border-slate-200 dark:border-slate-600">
          <div className="flex items-center gap-2 mb-1">
            <ImageIcon className="h-3 w-3 text-slate-500" />
            <span className="text-[10px] text-slate-600 dark:text-slate-400">Photos</span>
          </div>
          <div className="text-lg font-bold text-slate-900 dark:text-white">
            {totalPhotos}
          </div>
        </div>
        <div className="p-3 rounded-xl border-2 bg-slate-50 dark:bg-slate-700/50 border-slate-200 dark:border-slate-600">
          <div className="flex items-center gap-2 mb-1">
            <Duplicate className="h-3 w-3 text-slate-500" />
            <span className="text-[10px] text-slate-600 dark:text-slate-400">Duplicates</span>
          </div>
          <div className="text-lg font-bold text-slate-900 dark:text-white">
            {duplicateCount}
          </div>
        </div>
        <div className="p-3 rounded-xl border-2 bg-slate-50 dark:bg-slate-700/50 border-slate-200 dark:border-slate-600">
          <div className="flex items-center gap-2 mb-1">
            <ZapIcon className="h-3 w-3 text-slate-500" />
            <span className="text-[10px] text-slate-600 dark:text-slate-400">Rules</span>
          </div>
          <div className="text-lg font-bold text-slate-900 dark:text-white">
            {enabledRules}
          </div>
        </div>
      </div>

      {/* Quick Actions */}
      <div className="mb-4">
        <button
          type="button"
          onClick={handleRunOrganization}
          disabled={isOrganizing}
          className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-gradient-to-r from-teal-400 to-cyan-500 hover:from-teal-500 hover:to-cyan-600 disabled:from-slate-400 disabled:to-slate-500 text-white text-sm font-semibold rounded-lg transition-colors disabled:cursor-not-allowed"
        >
          <RefreshCw className={`h-4 w-4 ${isOrganizing ? 'animate-spin' : ''}`} />
          {isOrganizing ? 'Organizing...' : 'Run Organization'}
        </button>
      </div>

      {/* Organization Rules */}
      <div className="mb-4">
        <h4 className="font-semibold text-slate-900 dark:text-white text-sm mb-3">
          Organization Rules
        </h4>
        <div className="space-y-2">
          {rules.map((rule) => (
            <div
              key={rule.id}
              className={`p-4 rounded-lg border-2 ${
                rule.enabled
                  ? 'bg-teal-50 dark:bg-teal-950/30 border-teal-200 dark:border-teal-800'
                  : 'bg-slate-50 dark:bg-slate-700/50 border-slate-200 dark:border-slate-600'
              }`}
            >
              <div className="flex items-start justify-between mb-2">
                <div className="flex items-center gap-2">
                  <div className={`p-2 rounded-lg ${getRuleColor(rule.type)}`}>
                    {getRuleIcon(rule.type)}
                  </div>
                  <div>
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">
                      {rule.name}
                    </span>
                    <div className={`text-xs ${getRuleColor(rule.type)} capitalize`}>
                      {rule.type}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => handleToggleRule(rule.id)}
                    className={`relative w-10 h-5 rounded-full transition-colors ${
                      rule.enabled ? 'bg-teal-500' : 'bg-slate-300 dark:bg-slate-600'
                    }`}
                  >
                    <span
                      className={`absolute top-0.5 left-0.5 w-4 h-4 bg-white rounded-full transition-transform ${
                        rule.enabled ? 'translate-x-5' : ''
                      }`}
                    />
                  </button>
                </div>
              </div>

              <p className="text-xs text-slate-600 dark:text-slate-400 mb-2">
                {rule.description}
              </p>

              <div className="flex items-center justify-between">
                <span className="text-[10px] text-slate-500 dark:text-slate-400">
                  Auto-apply
                </span>
                <button
                  type="button"
                  onClick={() => handleToggleAutoApply(rule.id)}
                  className={`relative w-8 h-4 rounded-full transition-colors ${
                    rule.autoApply ? 'bg-teal-500' : 'bg-slate-300 dark:bg-slate-600'
                  }`}
                >
                  <span
                    className={`absolute top-0.5 left-0.5 w-3 h-3 bg-white rounded-full transition-transform ${
                      rule.autoApply ? 'translate-x-4' : ''
                    }`}
                  />
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Smart Albums */}
      <div className="mb-4">
        <h4 className="font-semibold text-slate-900 dark:text-white text-sm mb-3">
          Smart Albums
        </h4>
        <div className="space-y-2">
          {albums.map((album) => (
            <div
              key={album.id}
              className="p-4 rounded-lg border-2 bg-slate-50 dark:bg-slate-700/50 border-slate-200 dark:border-slate-600"
            >
              <div className="flex items-start justify-between mb-2">
                <div className="flex items-center gap-2">
                  <Layers className="h-4 w-4 text-slate-500" />
                  <div>
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">
                      {album.name}
                    </span>
                    <div className="text-xs text-slate-500 dark:text-slate-400 capitalize">
                      {album.type}
                    </div>
                  </div>
                </div>
                {album.autoGenerated && (
                  <span className="px-2 py-1 bg-teal-100 dark:bg-teal-900/30 text-teal-600 dark:text-teal-400 text-[10px] font-semibold rounded-full">
                    Auto
                  </span>
                )}
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <div className="text-[10px] text-slate-500 dark:text-slate-400">Photos</div>
                  <div className="text-xs text-slate-700 dark:text-slate-300">
                    {album.photoCount}
                  </div>
                </div>
                <div>
                  <div className="text-[10px] text-slate-500 dark:text-slate-400">Updated</div>
                  <div className="text-xs text-slate-700 dark:text-slate-300">
                    {album.lastUpdated.toLocaleDateString('vi-VN')}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Duplicate Detection */}
      <div className="mb-4">
        <h4 className="font-semibold text-slate-900 dark:text-white text-sm mb-3">
          Duplicate Detection
        </h4>
        <div className="space-y-2">
          {duplicates.map((group) => (
            <div
              key={group.id}
              className="p-4 rounded-lg border-2 bg-amber-50 dark:bg-amber-950/30 border-amber-200 dark:border-amber-800"
            >
              <div className="flex items-start justify-between mb-2">
                <div className="flex items-center gap-2">
                  <Duplicate className="h-4 w-4 text-amber-500" />
                  <div>
                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">
                      Duplicate Group
                    </span>
                    <div className="text-xs text-slate-500 dark:text-slate-400">
                      {group.photos.length} photos
                    </div>
                  </div>
                </div>
                <span className={`px-2 py-1 text-[10px] font-semibold rounded-full ${
                  group.action === 'keep_all'
                    ? 'bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-400'
                    : 'bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400'
                }`}>
                  {group.action.replace('_', ' ')}
                </span>
              </div>

              {/* Duplicate Photos */}
              <div className="space-y-2 mb-2">
                {group.photos.map((photo) => (
                  <div
                    key={photo.id}
                    className="p-3 rounded-lg border border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/50"
                  >
                    <div className="flex items-start justify-between mb-1">
                      <span className="text-xs font-medium text-slate-700 dark:text-slate-300">
                        {photo.name}
                      </span>
                      <span className="text-xs text-slate-500 dark:text-slate-400">
                        {(photo.similarity * 100).toFixed(0)}%
                      </span>
                    </div>
                    <div className="grid grid-cols-2 gap-2">
                      <div>
                        <div className="text-[10px] text-slate-500 dark:text-slate-400">Size</div>
                        <div className="text-xs text-slate-700 dark:text-slate-300">
                          {(photo.size / 1024).toFixed(1)}KB
                        </div>
                      </div>
                      <div>
                        <div className="text-[10px] text-slate-500 dark:text-slate-400">Date</div>
                        <div className="text-xs text-slate-700 dark:text-slate-300">
                          {photo.date.toLocaleDateString('vi-VN')}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Resolution Actions */}
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={() => handleResolveDuplicates(group.id, 'keep_best')}
                  className={`flex-1 px-2 py-1 text-xs font-semibold rounded-lg transition-colors ${
                    group.action === 'keep_best'
                      ? 'bg-green-500 text-white'
                      : 'bg-slate-200 dark:bg-slate-600 text-slate-700 dark:text-slate-300'
                  }`}
                >
                  Keep Best
                </button>
                <button
                  type="button"
                  onClick={() => handleResolveDuplicates(group.id, 'keep_newest')}
                  className={`flex-1 px-2 py-1 text-xs font-semibold rounded-lg transition-colors ${
                    group.action === 'keep_newest'
                      ? 'bg-green-500 text-white'
                      : 'bg-slate-200 dark:bg-slate-600 text-slate-700 dark:text-slate-300'
                  }`}
                >
                  Keep Newest
                </button>
                <button
                  type="button"
                  onClick={() => handleResolveDuplicates(group.id, 'keep_all')}
                  className={`flex-1 px-2 py-1 text-xs font-semibold rounded-lg transition-colors ${
                    group.action === 'keep_all'
                      ? 'bg-green-500 text-white'
                      : 'bg-slate-200 dark:bg-slate-600 text-slate-700 dark:text-slate-300'
                  }`}
                >
                  Keep All
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="mt-4 p-3 bg-teal-50 dark:bg-teal-950/30 border border-teal-200 dark:border-teal-900 rounded-lg">
        <p className="text-[10px] text-teal-700 dark:text-teal-400">
          <strong>Lưu ý:</strong> Tổ chức ảnh tự động sử dụng AI để phân loại và sắp xếp ảnh vào các album phù hợp với organization rules (date/location/category/person/event), smart album generation, duplicate detection with resolution actions (keep_best/keep_newest/keep_all), auto-apply settings, và run organization functionality.
        </p>
      </div>
    </div>
  );
}